apiVersion: v1
kind: Service
metadata:
  name: tsm2-tsm-node
  namespace: tsm
  labels:
    app.kubernetes.io/instance: tsm2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tsm-node
    app.kubernetes.io/version: 62.2.4
    helm.sh/chart: tsm-node-0.1.6
  annotations:
    meta.helm.sh/release-name: tsm2
    meta.helm.sh/release-namespace: tsm
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /ping
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-target-type: ip
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: sdk
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: mpc
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: tsm2
    app.kubernetes.io/name: tsm-node
  sessionAffinity: None

