# Default values for tsm-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
index: 0

# -- Environment variables to be passed to the TSM node deployment
env: {}

nodeConfig:
  # -- The name of the kubernetes generic secret containing the TSM configuration file. Secret is to be deployed separately from the chart. MUTUALLY EXCLUSIVE with configFile and configCSISecretStore
  configSecretName: ""    # Set a unique value relevant TSM node index

  # -- The name of the CSI Secret-Store secret containing the TSM configuration file. Secret is to be deployed separately from the chart. MUTUALLY EXCLUSIVE with configFile and configSecretName
  configCSISecretStore: {}
  # csi:
  #   driver: secrets-store.csi.k8s.io
  #   readOnly: true
  #   volumeAttributes:
  #     secretProviderClass: "tsm0-tsm-node"      # Set a unique value relevant TSM node index

  # -- The TSM configuration that will be mounted into the TSM node via a ConfigMap. Not recommended for production use. MUTUALLY EXCLUSIVE with configSecretName and configCSISecretStore
  configFile: ""

image:
  # -- Image to use for deploying the TSM node
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 2000
  # allowPrivilegeEscalation: false
  # seccompProfile:
  #   type: "RuntimeDefault"

# -- The primary service definition for the TSM node
sdkService:
  type: ClusterIP

# -- Optional. Only used for flexibility to expose the mpc port outside of the cluster.
mpcService: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Additional volumes on the output Deployment definition.
volumes: []

# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
