{{- if .Values.nodeConfig.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tsm-node.fullname" . }}
  labels:
    {{- include "tsm-node.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- .Values.nodeConfig.configFile | nindent 4 }}
{{- end }}