apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tsm0-tsm-node
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:111122223333:secret:tsm0-tsm-node-ABCDE"
        objectType: "secretsmanager"
        objectAlias: "config.toml"