apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tsm0-tsm-node
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                   # Set to true for using managed identity
    userAssignedIdentityID: 15623de8-3b34-4d11-b8bf-33678c2d7810   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: buildervault-testnet                             # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: tsm0-tsm-node
          objectType: secret
          objectAlias: config.toml
    tenantId: 804712c2-1d3e-4eda-be6f-2f4bdbc36300                  # The tenant ID of the key vault