apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db2
  template:
    metadata:
      labels:
        app: postgres-db2
    spec:
      containers:
      - name: postgres
        image: postgres:15.4-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "db2user"
        - name: POSTGRES_PASSWORD
          value: "db2password"
        - name: POSTGRES_DB
          value: "db2"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db2
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-db2